// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Action    string             `json:"action"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CoachQuery struct {
	ID           int64              `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	Question     string             `json:"question"`
	SourcesCount int32              `json:"sources_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	CreatedBy    int64              `json:"created_by"`
	SourceDocIds []int64            `json:"source_doc_ids"`
	Status       string             `json:"status"`
	Settings     []byte             `json:"settings"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Department   pgtype.Text        `json:"department"`
	Approved     pgtype.Bool        `json:"approved"`
	ReviewStatus pgtype.Text        `json:"review_status"`
	ReviewNotes  pgtype.Text        `json:"review_notes"`
	ApprovedBy   pgtype.Int8        `json:"approved_by"`
	Capacity     pgtype.Int4        `json:"capacity"`
}

type CourseGenerationJob struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	Request   []byte             `json:"request"`
	Steps     []byte             `json:"steps"`
	Modules   []byte             `json:"modules"`
	Result    []byte             `json:"result"`
	Error     pgtype.Text        `json:"error"`
	CourseID  pgtype.Int8        `json:"course_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CourseItem struct {
	ID        int64              `json:"id"`
	CourseID  int64              `json:"course_id"`
	ModuleID  pgtype.Int8        `json:"module_id"`
	ItemType  string             `json:"item_type"`
	SortOrder int32              `json:"sort_order"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CourseScore struct {
	UserID      int64              `json:"user_id"`
	CourseID    int64              `json:"course_id"`
	Score       int32              `json:"score"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Department struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	FilePath     string             `json:"file_path"`
	Status       string             `json:"status"`
	UploadedBy   pgtype.Int8        `json:"uploaded_by"`
	TotalChunks  int32              `json:"total_chunks"`
	ChunksDone   int32              `json:"chunks_done"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Approved     pgtype.Bool        `json:"approved"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ReviewStatus pgtype.Text        `json:"review_status"`
	ReviewNotes  pgtype.Text        `json:"review_notes"`
}

type DocumentChunk struct {
	ID          int64              `json:"id"`
	DocumentID  int64              `json:"document_id"`
	ChunkIndex  int32              `json:"chunk_index"`
	Content     string             `json:"content"`
	PageNumber  pgtype.Int4        `json:"page_number"`
	SourceLabel pgtype.Text        `json:"source_label"`
	Embedding   pgvector.Vector    `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	CourseID    int64              `json:"course_id"`
	Status      string             `json:"status"`
	ProgressPct pgtype.Numeric     `json:"progress_pct"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DroppedAt   pgtype.Timestamptz `json:"dropped_at"`
}

type ItemProgress struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CourseID   int64              `json:"course_id"`
	ItemID     int64              `json:"item_id"`
	Answer     []byte             `json:"answer"`
	IsCorrect  pgtype.Bool        `json:"is_correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

type LearningPath struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedBy   int64              `json:"created_by"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LearningPathCourse struct {
	ID             int64 `json:"id"`
	LearningPathID int64 `json:"learning_path_id"`
	CourseID       int64 `json:"course_id"`
	SortOrder      int32 `json:"sort_order"`
	IsRequired     bool  `json:"is_required"`
}

type LearningPathEnrollment struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	LearningPathID int64              `json:"learning_path_id"`
	Status         string             `json:"status"`
	ProgressPct    pgtype.Numeric     `json:"progress_pct"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	DroppedAt      pgtype.Timestamptz `json:"dropped_at"`
}

type LearningPreference struct {
	UserID          int64              `json:"user_id"`
	LearningStyle   string             `json:"learning_style"`
	DifficultyLevel string             `json:"difficulty_level"`
	PreferredTopics []string           `json:"preferred_topics"`
	Theta           float64            `json:"theta"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LessonProgress struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	CourseID      int64              `json:"course_id"`
	CurrentModule int32              `json:"current_module"`
	Completed     bool               `json:"completed"`
	ScorePct      pgtype.Numeric     `json:"score_pct"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type Module struct {
	ID          int64              `json:"id"`
	CourseID    int64              `json:"course_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	Link      string             `json:"link"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type PracticeSession struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Topic         string             `json:"topic"`
	QuestionCount int32              `json:"question_count"`
	CorrectCount  int32              `json:"correct_count"`
	ScorePct      pgtype.Numeric     `json:"score_pct"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type RolePermission struct {
	Role         string `json:"role"`
	PermissionID int64  `json:"permission_id"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserDepartment struct {
	UserID       int64 `json:"user_id"`
	DepartmentID int64 `json:"department_id"`
}

type UserRole struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

type UserStreak struct {
	UserID     int64              `json:"user_id"`
	StreakDate pgtype.Date        `json:"streak_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
