// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Course struct {
	ID           int64
	Title        string
	Description  string
	CreatedBy    int64
	SourceDocIds []int64
	Status       string
	Settings     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Department   pgtype.Text
	Approved     pgtype.Bool
}

type CourseItem struct {
	ID        int64
	CourseID  int64
	ItemType  string
	SortOrder int32
	Data      []byte
	CreatedAt pgtype.Timestamptz
}

type Document struct {
	ID         int64
	Title      string
	FilePath   string
	Status     string
	UploadedBy pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	Approved   pgtype.Bool
}

type DocumentChunk struct {
	ID          int64
	DocumentID  int64
	ChunkIndex  int32
	Content     string
	PageNumber  pgtype.Int4
	SourceLabel pgtype.Text
	Embedding   pgvector.Vector
	CreatedAt   pgtype.Timestamptz
}

type LearningPreference struct {
	UserID          int64
	LearningStyle   string
	DifficultyLevel string
	PreferredTopics []string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Permission struct {
	ID   int64
	Name string
}

type PracticeSession struct {
	ID            int64
	UserID        int64
	Topic         string
	QuestionCount int32
	CorrectCount  int32
	ScorePct      pgtype.Numeric
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type RolePermission struct {
	Role         string
	PermissionID int64
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
